### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Patrikkk** [alexcw923/Virtual-Girlfriend#1]
PS H:\GitHub\ChatBot-GPT> python main.py
Traceback (most recent call last):
  File "H:\GitHub\ChatBot-GPT\main.py", line 1, in <module>
    from ChatBot.JOI import JOI
  File "H:\GitHub\ChatBot-GPT\ChatBot\JOI.py", line 1, in <module>
    from ChatBot.ChatBot import Bot
  File "H:\GitHub\ChatBot-GPT\ChatBot\ChatBot.py", line 3, in <module>
    import whisper
  File "C:\Users\patri\AppData\Local\Programs\Python\Python310\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Users\patri\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

Issue seems to be within/through whisper. I have latest version installed 1.1.10. Running Python3

**Comment by alexcw923** [comment]
What Operating System are you on? It seems to work well on Mac OS X.
